//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.18 at 02:18:19 PM IST 
//

package com.cg.osce.apibuilder.pojo;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.node.ObjectNode;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="swagger" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="info"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="termsOfService" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="contact"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="license"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="tags" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="externalDocs" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "swagger", "info", "host", "basepath", "tags", "paths", "definitions" })
@XmlRootElement(name = "swaggerSchema")
@JsonInclude(Include.NON_NULL)
public class SwaggerSchema {

	@XmlElement(required = true)
	protected String swagger;
	@XmlElement(required = true)
	protected SwaggerSchema.Info info;
	@XmlElement(required = true)
	protected String host;
	@XmlElement(required = true)
	protected String basePath;
	@XmlElement(required = false)
	protected String[] schemes;
	/**
	 * @XmlElement(required = false) protected List<SwaggerSchema.Tags> tags;
	 **/
	@XmlElement(required = false)
	protected ObjectNode paths;
	@XmlElement(required = false)
	protected ObjectNode definitions;

	public String getHost() {
		return host;
	}

	public String[] getSchemes() {
		return schemes;
	}

	public void setSchemes(String[] schemes) {
		this.schemes = schemes;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public String getBasePath() {
		return basePath;
	}

	public void setBasePath(String basePath) {
		this.basePath = basePath;
	}

	public ObjectNode getDefinitions() {
		return definitions;
	}

	public void setDefinitions(ObjectNode definitions) {
		this.definitions = definitions;
	}

	/**
	 * Gets the value of the swagger property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public String getSwagger() {
		return swagger;
	}

	public ObjectNode getPaths() {
		return paths;
	}

	public void setPaths(ObjectNode paths) {
		this.paths = paths;
	}

	/**
	 * public void setTags(List<SwaggerSchema.Tags> tags) { this.tags = tags; }
	 * 
	 * /** Sets the value of the swagger property.
	 * 
	 * @param value allowed object is {@link BigDecimal }
	 * 
	 */
	public void setSwagger(String value) {
		this.swagger = value;
	}

	/**
	 * Gets the value of the info property.
	 * 
	 * @return possible object is {@link SwaggerSchema.Info }
	 * 
	 */
	public SwaggerSchema.Info getInfo() {
		return info;
	}

	/**
	 * Sets the value of the info property.
	 * 
	 * @param value allowed object is {@link SwaggerSchema.Info }
	 * 
	 */
	public void setInfo(SwaggerSchema.Info value) {
		this.info = value;
	}

	/**
	 * Gets the value of the tags property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the tags property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getTags().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SwaggerSchema.Tags }
	 * 
	 * 
	 */
	/**
	 * public List<SwaggerSchema.Tags> getTags() { if (tags == null) { tags = new
	 * ArrayList<SwaggerSchema.Tags>(); } return this.tags; }
	 **/

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="termsOfService" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="contact"&gt;
	 *           &lt;complexType&gt;
	 *             &lt;complexContent&gt;
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *                 &lt;sequence&gt;
	 *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                 &lt;/sequence&gt;
	 *               &lt;/restriction&gt;
	 *             &lt;/complexContent&gt;
	 *           &lt;/complexType&gt;
	 *         &lt;/element&gt;
	 *         &lt;element name="license"&gt;
	 *           &lt;complexType&gt;
	 *             &lt;complexContent&gt;
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *                 &lt;sequence&gt;
	 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                 &lt;/sequence&gt;
	 *               &lt;/restriction&gt;
	 *             &lt;/complexContent&gt;
	 *           &lt;/complexType&gt;
	 *         &lt;/element&gt;
	 *       &lt;/sequence&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "description", "version", "title", "termsOfService", "contact", "license" })
	@JsonInclude(Include.NON_NULL)
	public static class Info {

		@XmlElement(required = true)
		protected String description;
		@XmlElement(required = true)
		protected String version;
		@XmlElement(required = true)
		protected String title;
		@XmlElement(required = true)
		protected String termsOfService;
		@XmlElement(required = true)
		protected SwaggerSchema.Info.Contact contact;
		@XmlElement(required = true)
		protected SwaggerSchema.Info.License license;

		/**
		 * Gets the value of the description property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDescription() {
			return description;
		}

		/**
		 * Sets the value of the description property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setDescription(String value) {
			this.description = value;
		}

		/**
		 * Gets the value of the version property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getVersion() {
			return version;
		}

		/**
		 * Sets the value of the version property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setVersion(String value) {
			this.version = value;
		}

		/**
		 * Gets the value of the title property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTitle() {
			return title;
		}

		/**
		 * Sets the value of the title property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setTitle(String value) {
			this.title = value;
		}

		/**
		 * Gets the value of the termsOfService property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTermsOfService() {
			return termsOfService;
		}

		/**
		 * Sets the value of the termsOfService property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setTermsOfService(String value) {
			this.termsOfService = value;
		}

		/**
		 * Gets the value of the contact property.
		 * 
		 * @return possible object is {@link SwaggerSchema.Info.Contact }
		 * 
		 */
		public SwaggerSchema.Info.Contact getContact() {
			return contact;
		}

		/**
		 * Sets the value of the contact property.
		 * 
		 * @param value allowed object is {@link SwaggerSchema.Info.Contact }
		 * 
		 */
		public void setContact(SwaggerSchema.Info.Contact value) {
			this.contact = value;
		}

		/**
		 * Gets the value of the license property.
		 * 
		 * @return possible object is {@link SwaggerSchema.Info.License }
		 * 
		 */
		public SwaggerSchema.Info.License getLicense() {
			return license;
		}

		/**
		 * Sets the value of the license property.
		 * 
		 * @param value allowed object is {@link SwaggerSchema.Info.License }
		 * 
		 */
		public void setLicense(SwaggerSchema.Info.License value) {
			this.license = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 * 
		 * <pre>
		 * &lt;complexType&gt;
		 *   &lt;complexContent&gt;
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
		 *       &lt;sequence&gt;
		 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *       &lt;/sequence&gt;
		 *     &lt;/restriction&gt;
		 *   &lt;/complexContent&gt;
		 * &lt;/complexType&gt;
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "email" })
		@JsonInclude(Include.NON_NULL)
		public static class Contact {

			@XmlElement(required = true)
			protected String email;

			/**
			 * Gets the value of the email property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getEmail() {
				return email;
			}

			/**
			 * Sets the value of the email property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setEmail(String value) {
				this.email = value;
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 * 
		 * <pre>
		 * &lt;complexType&gt;
		 *   &lt;complexContent&gt;
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
		 *       &lt;sequence&gt;
		 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *       &lt;/sequence&gt;
		 *     &lt;/restriction&gt;
		 *   &lt;/complexContent&gt;
		 * &lt;/complexType&gt;
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "name", "url" })
		@JsonInclude(Include.NON_NULL)
		public static class License {

			@XmlElement(required = true)
			protected String name;
			@XmlElement(required = true)
			protected String url;

			/**
			 * Gets the value of the name property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getName() {
				return name;
			}

			/**
			 * Sets the value of the name property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setName(String value) {
				this.name = value;
			}

			/**
			 * Gets the value of the url property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getUrl() {
				return url;
			}

			/**
			 * Sets the value of the url property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setUrl(String value) {
				this.url = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="externalDocs" minOccurs="0"&gt;
	 *           &lt;complexType&gt;
	 *             &lt;complexContent&gt;
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *                 &lt;sequence&gt;
	 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                 &lt;/sequence&gt;
	 *               &lt;/restriction&gt;
	 *             &lt;/complexContent&gt;
	 *           &lt;/complexType&gt;
	 *         &lt;/element&gt;
	 *       &lt;/sequence&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "name", "description", "externalDocs" })
	@JsonInclude(Include.NON_NULL)
	public static class Tags {

		@XmlElement(required = true)
		protected String name;
		@XmlElement(required = true)
		protected String description;
		@XmlElement(required = true)
		protected String host;
		@XmlElement(required = true)
		protected String basepath;
		@XmlElement(required = false)
		protected SwaggerSchema.Tags.ExternalDocs externalDocs;

		/**
		 * Gets the value of the name property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getName() {
			return name;
		}

		public String getHost() {
			return host;
		}

		public void setHost(String host) {
			this.host = host;
		}

		public String getBasepath() {
			return basepath;
		}

		public void setBasepath(String basepath) {
			this.basepath = basepath;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setName(String value) {
			this.name = value;
		}

		/**
		 * Gets the value of the description property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDescription() {
			return description;
		}

		/**
		 * Sets the value of the description property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setDescription(String value) {
			this.description = value;
		}

		/**
		 * Gets the value of the externalDocs property.
		 * 
		 * @return possible object is {@link SwaggerSchema.Tags.ExternalDocs }
		 * 
		 */
		public SwaggerSchema.Tags.ExternalDocs getExternalDocs() {
			return externalDocs;
		}

		/**
		 * Sets the value of the externalDocs property.
		 * 
		 * @param value allowed object is {@link SwaggerSchema.Tags.ExternalDocs }
		 * 
		 */
		public void setExternalDocs(SwaggerSchema.Tags.ExternalDocs value) {
			this.externalDocs = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 * 
		 * <pre>
		 * &lt;complexType&gt;
		 *   &lt;complexContent&gt;
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
		 *       &lt;sequence&gt;
		 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *       &lt;/sequence&gt;
		 *     &lt;/restriction&gt;
		 *   &lt;/complexContent&gt;
		 * &lt;/complexType&gt;
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "description", "url" })
		@JsonInclude(Include.NON_NULL)
		public static class ExternalDocs {

			@XmlElement(required = true)
			protected String description;
			@XmlElement(required = true)
			protected String url;

			/**
			 * Gets the value of the description property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDescription() {
				return description;
			}

			/**
			 * Sets the value of the description property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setDescription(String value) {
				this.description = value;
			}

			/**
			 * Gets the value of the url property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getUrl() {
				return url;
			}

			/**
			 * Sets the value of the url property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setUrl(String value) {
				this.url = value;
			}

		}

	}

}
